name: 'Gluon Build License'
description: 'Action to configure your Gluon license.'
branding:
  icon: check-square
  color: blue
inputs:
  gluon-license:
    required: true
runs:
  using: "composite"
  steps: 
    - run: printf "${{ inputs.gluon-license }}" > src/main/resources/gluonmobile.license
      shell: bash
